// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: export.sql

package db

import (
	"context"
)

const exportAllTeams = `-- name: ExportAllTeams :many
SELECT id, name, number_of_people, round_qualified, code
FROM teams
`

func (q *Queries) ExportAllTeams(ctx context.Context) ([]Team, error) {
	rows, err := q.db.Query(ctx, exportAllTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Team
	for rows.Next() {
		var i Team
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NumberOfPeople,
			&i.RoundQualified,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAllUsers = `-- name: ExportAllUsers :many
SELECT id, team_id, first_name, last_name, email, phone_no, gender, reg_no, vit_email, hostel_block, room_no, github_profile, password, role, is_leader, is_verified, is_banned, is_profile_complete
FROM users
`

func (q *Queries) ExportAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, exportAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.PhoneNo,
			&i.Gender,
			&i.RegNo,
			&i.VitEmail,
			&i.HostelBlock,
			&i.RoomNo,
			&i.GithubProfile,
			&i.Password,
			&i.Role,
			&i.IsLeader,
			&i.IsVerified,
			&i.IsBanned,
			&i.IsProfileComplete,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
