// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: submission.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSubmissionByTeamID = `-- name: GetSubmissionByTeamID :one
SELECT id, github_link, figma_link, ppt_link, other_link, team_id FROM submission WHERE team_id = $1
`

func (q *Queries) GetSubmissionByTeamID(ctx context.Context, teamID uuid.UUID) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByTeamID, teamID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.GithubLink,
		&i.FigmaLink,
		&i.PptLink,
		&i.OtherLink,
		&i.TeamID,
	)
	return i, err
}
