// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: teams.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTeamIDByCode = `-- name: GetTeamIDByCode :one
SELECT id FROM teams WHERE code = $1
`

func (q *Queries) GetTeamIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeamIDByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
