-- +goose Up
ALTER TABLE teams ADD CONSTRAINT fk_teams_users FOREIGN KEY (users) REFERENCES users (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE teams ADD CONSTRAINT fk_teams_score FOREIGN KEY (id) REFERENCES score (team_id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE teams ADD CONSTRAINT fk_teams_submission FOREIGN KEY (submission) REFERENCES submission (id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE users ADD CONSTRAINT fk_users_teams FOREIGN KEY (team_id) REFERENCES teams (id) ON UPDATE CASCADE ON DELETE CASCADE;

-- +goose Down
ALTER TABLE teams
DROP CONSTRAINT fk_teams_users;

ALTER TABLE teams
DROP CONSTRAINT fk_teams_score;

ALTER TABLE teams
DROP CONSTRAINT fk_teams_submission;

ALTER TABLE users
DROP CONSTRAINT fk_users_teams;
