-- +goose Up
ALTER TABLE score
ADD COLUMN points1 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN points2 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN points3 INTEGER NOT NULL DEFAULT 0,
ADD COLUMN comment TEXT;

-- +goose Down
ALTER TABLE score
DROP COLUMN points1,
DROP COLUMN points2,
DROP COLUMN points3,
DROP COLUMN comment;